spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: src/main/resources/migration_script.sql
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 898313663527-uhui1u4verpq4joam69ulk4punetm9tb.apps.googleusercontent.com
            clientSecret: 6sIBJ8AshLW4YCwybqDHmSMd
            scope: email,profile

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris: http://localhost:8080/logincallback

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        web: DEBUG
