spring:
  jpa:
    properties:
      hibernate:
        format-sql: true
        generate_statistics: true
  datasource:
    url: jdbc:sqlserver://healthtech-api.database.windows.net:1433;database=healthtech;user=djebos@healthtech-api;password=4326650Db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    hikari:
      maximum-pool-size: 50 # 1 connection in pool for 4 tomcat threads
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 898313663527-uhui1u4verpq4joam69ulk4punetm9tb.apps.googleusercontent.com
            clientSecret: 6sIBJ8AshLW4YCwybqDHmSMd
            scope: email,profile,https://www.googleapis.com/auth/calendar

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris: https://healthtech-pwa-dev.westeurope.azurecontainer.io
