server:
  port: 8081
  servlet:
    context-path: /rest

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
