server:
  port: 8081
  servlet:
    context-path: /rest

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      fail_on_empty_beans: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration/{vendor}

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,env,logfile,loggers

springdoc:
  api-docs:
    path: /api-docs

logging:
  file:
    name: logs/api-service.log