create table glucose_measurements
(
    glucose float4 not null,
    uid     uuid   not null,
    primary key (uid)
);

create table measurements
(
    uid          uuid not null,
    created_time timestamp,
    unit         varchar(255),
    version      int4,
    user_id      int8 not null,
    primary key (uid)
);

create table pressure_measurements
(
    diastolic int4 not null,
    systolic  int4 not null,
    uid       uuid not null,
    primary key (uid)
);

create table pulse_measurements
(
    pulse int4 not null,
    uid   uuid not null,
    primary key (uid)
);

create table roles
(
    id            int8 generated by default as identity,
    creation_time timestamp,
    description   varchar(255),
    uid           varchar(255),
    primary key (id)
);

create table temp_measurements
(
    temp float4 not null,
    uid  uuid   not null,
    primary key (uid)
);

create table users
(
    id            int8 generated by default as identity,
    auth          varchar(255),
    creation_time timestamp,
    email         varchar(255) not null,
    is_active     boolean default true,
    name          varchar(255),
    password      varchar(255),
    picture_url   varchar(255),
    primary key (id)
);

create table users_roles
(
    user_id int8 not null,
    role_id int8 not null,
    primary key (user_id, role_id)
);

create table weight_measurements
(
    weight float4 not null,
    uid    uuid   not null,
    primary key (uid)
);

alter table if exists roles
    add constraint uid_uc unique (uid);

alter table if exists users
    add constraint email_uc unique (email);

alter table if exists glucose_measurements
    add constraint root_measurement_fk
        foreign key (uid) references measurements;

alter table if exists measurements
    add constraint user_id_fk
        foreign key (user_id) references users;

alter table if exists pressure_measurements
    add constraint root_measurement_fk
        foreign key (uid) references measurements;

alter table if exists pulse_measurements
    add constraint root_measurement_fk
        foreign key (uid) references measurements;

alter table if exists temp_measurements
    add constraint root_measurement_fk
        foreign key (uid) references measurements;

alter table if exists users_roles
    add constraint role_id_fk
        foreign key (role_id) references roles;

alter table if exists users_roles
    add constraint user_id_fk
        foreign key (user_id) references users;

alter table if exists weight_measurements
    add constraint root_measurement_fk
        foreign key (uid) references measurements
